# Generated by Django 4.1.4 on 2023-01-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('demand', models.TextField(verbose_name='Востребованность')),
                ('geography', models.TextField(verbose_name='География')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('lastvac', models.TextField(verbose_name='Последние вакансии')),
            ],
        ),
    ]
